name: FL provision resources STRIDES

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'fedlearn' 
        type: string
  
      NIC_Name:
        description: 'Name of precreated NIC'
        required: true
        default: 'fedlearn-nic-primary'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Provision resources
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}"
        RANDOMQUALIFIER="$RANDOM"
        
        az vm create -n fedserver --image microsoft-dsvm:ubuntu-2004:2004-gen2:latest --authentication-type password \
        --admin-username fedserveradmin \
        --admin-password ${{ secrets.VM_PASSWORD }} \
        --nics ${{ github.event.inputs.NIC_Name }}
                
        az ml workspace create -n Asia-Hospital --location eastus2 --resource-group ${{ github.event.inputs.resource_group }}
        az ml compute create --type ComputeInstance --name FedClientAsia$RANDOMQUALIFIER --workspace-name Asia-Hospital --resource-group ${{ github.event.inputs.resource_group }}
        az ml workspace create -n Europe-Hospital --location eastus2 --resource-group ${{ github.event.inputs.resource_group }}
        az ml compute create --type ComputeInstance --name FedClientEurope$RANDOMQUALIFIER --workspace-name Europe-Hospital --resource-group ${{ github.event.inputs.resource_group }}
        az ml workspace create -n US-Hospital --location eastus2 --resource-group ${{ github.event.inputs.resource_group }}
        az ml compute create --type ComputeInstance --name FedClientUS$RANDOMQUALIFIER --workspace-name US-Hospital --resource-group ${{ github.event.inputs.resource_group }}
